# Project: Snake
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/APP/Dev-Cpp/MinGW64/lib" -L"D:/APP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"D:/Drive_micky/001_Cpp/002_Graphics-library/001_EasyX/program/Snake/irrKlang-64bit-1.6.0/lib" -L"D:/Drive_micky/001_Cpp/002_Graphics-library/001_EasyX/program/Snake/irrKlang-64bit-1.6.0/lib/Winx64-visualStudio" libeasyx.a ws2_32.dll irrKlang-64bit-1.6.0/lib/Winx64-visualStudio/irrKlang.exp irrKlang-64bit-1.6.0/lib/Winx64-visualStudio/irrKlang.lib -g3
INCS     = -I"D:/APP/Dev-Cpp/MinGW64/include" -I"D:/APP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/APP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/APP/Dev-Cpp/MinGW64/include" -I"D:/APP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/APP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/APP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Snake.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11 -g3
CFLAGS   = $(INCS) -std=gnu++11 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
